"""Parser tests for core/ingest/xrdml against the golden XRDML fixtures
(generated by benchmarks/protocols/generate_fixtures.py, GSAS-II v5.6.3).
"""
import numpy as np
import pytest

from core.ingest import XRDMLError, parse_xrdml

FIX = "tests/fixtures/xrdml"


def load(name: str):
    return parse_xrdml(f"{FIX}/{name}")


# ---------------------------------------------------------------- happy paths

def test_parse_cu_pbso4_grid_and_meta():
    p = load("cu_PbSO4.xrdml")
    assert p.npts == 6251
    assert p.tth[0] == pytest.approx(15.0)
    assert p.tth[-1] == pytest.approx(15.0 + 0.02 * 6250)
    assert p.instrument.step == pytest.approx(0.02)
    assert p.instrument.anode == "Cu"
    assert p.instrument.wavelengths[0] == pytest.approx(1.5405, abs=1e-4)
    assert p.instrument.wavelengths[1] == pytest.approx(1.5443, abs=1e-4)
    assert "2THETA" in p.instrument.scan_axis.upper()
    assert p.sample_name == "PbSO4"
    assert p.intensity.shape == p.tth.shape


def test_parse_cu_pbso4_physics():
    p = load("cu_PbSO4.xrdml")
    imax = int(np.argmax(p.intensity))
    assert 29.4 <= p.tth[imax] <= 30.0, "PbSO4 Cu top peak ~29.7 deg"
    assert p.intensity[imax] > 1e6


def test_parse_fe_pbso4_physics():
    p = load("fe_PbSO4.xrdml")
    assert p.instrument.anode == "Fe"
    assert p.instrument.wavelengths[0] == pytest.approx(1.9360, abs=1e-4)
    imax = int(np.argmax(p.intensity))
    assert 37.2 <= p.tth[imax] <= 37.9, "same d as Cu pattern, kinematically shifted"


def test_parse_cu_quartz_physics():
    p = load("cu_quartz.xrdml")
    imax = int(np.argmax(p.intensity))
    assert 25.5 <= p.tth[imax] <= 26.2
    assert "SiO2" in p.sample_name


def test_parse_base64_variant_equals_ascii():
    ascii_p = load("cu_PbSO4.xrdml")
    b64_p = load("base64_PbSO4.xrdml")
    assert np.array_equal(b64_p.intensity, ascii_p.intensity)
    assert b64_p.sample_name == ascii_p.sample_name
    assert b64_p.npts == ascii_p.npts


def test_parse_nonamespace_variant():
    p = load("nonamespace_quartz.xrdml")
    assert p.npts == 6251
    assert p.instrument.anode == "Cu"
    assert "SiO2" in p.sample_name


def test_parse_accepts_bytes_and_fileobj(tmp_path):
    raw = open(f"{FIX}/cu_PbSO4.xrdml", "rb").read()
    pb = parse_xrdml(raw)
    assert pb.npts == 6251
    f = open(f"{FIX}/cu_PbSO4.xrdml")
    pf = parse_xrdml(f)
    assert pf.npts == 6251
    f.close()


# ----------------------------------------------------------------- error paths

def test_missing_file_raises():
    with pytest.raises(XRDMLError):
        parse_xrdml(f"{FIX}/does_not_exist.xrdml")


def test_malformed_xml_raises():
    with pytest.raises(XRDMLError):
        parse_xrdml("<xrdMeasurements><broken>")


def test_wrong_root_raises():
    with pytest.raises(XRDMLError):
        parse_xrdml("<?xml version='1.0'?><measurements/>")


def test_empty_intensities_raises():
    xml = """<?xml version="1.0"?>
<xrdMeasurements xmlns="http://www.xpdd.org/xrdml/1.0">
 <xrdMeasurement count="1" measurementType="Scan">
  <sample id="s"><name>x</name></sample>
  <scan count="1"><xrdElement id="e">
    <commonParameters>
      <goniometer><thetaMin>5</thetaMin><stepSize>0.02</stepSize></goniometer>
    </commonParameters>
    <intensities>   </intensities>
  </xrdElement></scan>
 </xrdMeasurement>
</xrdMeasurements>"""
    with pytest.raises(XRDMLError):
        parse_xrdml(xml)


def test_non_numeric_intensities_raises():
    xml = """<?xml version="1.0"?>
<xrdMeasurements xmlns="http://www.xpdd.org/xrdml/1.0">
 <xrdMeasurement count="1" measurementType="Scan">
  <sample id="s"><name>x</name></sample>
  <scan count="1"><xrdElement id="e">
    <commonParameters>
      <goniometer><thetaMin>5</thetaMin><stepSize>0.02</stepSize></goniometer>
    </commonParameters>
    <intensities>abc 12 3</intensities>
  </xrdElement></scan>
 </xrdMeasurement>
</xrdMeasurements>"""
    with pytest.raises(XRDMLError):
        parse_xrdml(xml)


def test_no_goniometer_raises():
    xml = """<?xml version="1.0"?>
<xrdMeasurements xmlns="http://www.xpdd.org/xrdml/1.0">
 <xrdMeasurement count="1" measurementType="Scan">
  <sample id="s"><name>x</name></sample>
  <scan count="1"><xrdElement id="e">
    <intensities>1 2 3</intensities>
  </xrdElement></scan>
 </xrdMeasurement>
</xrdMeasurements>"""
    with pytest.raises(XRDMLError):
        parse_xrdml(xml)